# Generated by Django 4.2.4 on 2023-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_jobrequest_id_alter_servicerequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
